project:
  type: website
  output-dir: ../_site/ru

website:
  title: "–ù–∏–∫–æ–ª–∞–π –ú–∞–ª—å–∫–æ–≤—Å–∫–∏–π"
  description: "–ü–µ—Ä—Å–æ–Ω–∞–ª—å–Ω—ã–π —Å–∞–π—Ç –∏ –±–ª–æ–≥"
  site-url: https://malkovsky.github.io/personal-site/ru
  repo-url: https://github.com/Malkovsky/personal-site
  repo-actions: [edit, issue]
  
  navbar:
    background: primary
    search: true
    left:
      - text: "–ì–ª–∞–≤–Ω–∞—è"
        href: index.qmd
      - text: "–û–±–æ –º–Ω–µ"
        href: about.qmd
      - text: "–ë–ª–æ–≥"
        href: blog/index.qmd
      - text: "–ü—Ä–æ–µ–∫—Ç—ã"
        href: projects/index.qmd
      # - text: "–ü—É–±–ª–∏–∫–∞—Ü–∏–∏"
      #   href: publications.qmd
      - text: "–†–µ–∑—é–º–µ"
        href: resume.qmd
      - text: "–ö–æ–Ω—Ç–∞–∫—Ç—ã"
        href: contact.qmd
    
    right:
      - text: "üá¨üáß EN"
        href: ../en/index.html
        aria-label: "–ü–µ—Ä–µ–∫–ª—é—á–∏—Ç—å –Ω–∞ –∞–Ω–≥–ª–∏–π—Å–∫–∏–π"
      - icon: github
        href: https://github.com/Malkovsky
        aria-label: "GitHub"
      - icon: linkedin
        href: https://linkedin.com/in/nikolay-malkovsky-a5479b140/
        aria-label: "LinkedIn"
      - text: "![](https://habrastorage.org/getpro/habr/company/7e4/7b8/e31/7e47b8e31d0efe9f398461278a16a357.png){width=20px}"
        href: https://habr.com/ru/users/malkovsky/
        aria-label: "Habr"

  page-footer:
    left: |
      Copyright ¬© 2026 –ù–∏–∫–æ–ª–∞–π –ú–∞–ª—å–∫–æ–≤—Å–∫–∏–π
    right:
      - icon: github
        href: https://github.com/Malkovsky
      - icon: envelope
        href: mailto:malkovskynv@gmail.com

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: ../styles/custom.scss
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    anchor-sections: true
    smooth-scroll: true
    lang: ru
    
# Execution options for Jupyter notebooks
execute:
  freeze: auto
  cache: true
